{
	"version": 1735885226,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/slickerthanaverage_road_and_city_to_vegas_2d_cartoon_style_a54258c7096142689bfe04d83ae768bb-sheet0.png",
		"images/lensflarelightspecialeffectbackgroundfreepng2-sheet0.png",
		"images/imagephotoroom-sheet0.png",
		"images/freddyright1.png",
		"images/freddyleft1.png",
		"images/freddyright2.png",
		"images/right3.png",
		"images/freddyleft2.png",
		"images/freddyleft3.png",
		"images/horrowhallwayvignette-sheet0.png",
		"images/dark-sheet0.png",
		"images/freddyr-sheet0.png",
		"images/horrowhallwayjasonfreddy-sheet0.png",
		"images/horrowhallwayjasonfreddy-sheet1.png",
		"images/horrowhallwayjasonfreddy-sheet2.png",
		"images/play-sheet0.png",
		"images/dl3-sheet0.png",
		"images/dr2-sheet0.png",
		"images/dl2-sheet0.png",
		"images/dr1-sheet0.png",
		"images/dl1-sheet0.png",
		"images/asset14x-sheet0.png",
		"images/asset14x-sheet1.png",
		"images/jasonleft1.png",
		"images/jasonl-sheet0.png",
		"images/jasonleft2.png",
		"images/jasonleft3.png",
		"images/jasonright1.png",
		"images/jasonright2.png",
		"images/dark1-sheet0.png",
		"images/dark1-sheet1.png",
		"images/dark1-sheet2.png",
		"images/dark1-sheet3.png",
		"images/dark1-sheet4.png",
		"images/dark1-sheet5.png",
		"media/door.m4a",
		"media/door.ogg",
		"media/laugh.m4a",
		"media/laugh.ogg",
		"media/scream 1.m4a",
		"media/scream 1.ogg",
		"media/scream 2.m4a",
		"media/scream 2.ogg",
		"media/gameover 2.m4a",
		"media/gameover 2.ogg",
		"media/gameover 1.m4a",
		"media/gameover 1.ogg",
		"media/shoot-6-81136.m4a",
		"media/shoot-6-81136.ogg",
		"media/horror hallway - bgm.m4a",
		"media/horror hallway - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}